// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtptVJtN3z43r-GYQBVNg55tgbntfZE8',
    appId: '1:975712420973:web:287564b15c6b55c1fceb64',
    messagingSenderId: '975712420973',
    projectId: 'adiuva-aa007',
    authDomain: 'adiuva-aa007.firebaseapp.com',
    storageBucket: 'adiuva-aa007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-iKUBOGQbQtKjufbSSsor2yQHS2w1R1U',
    appId: '1:975712420973:android:b6ad5b1f9ec12a80fceb64',
    messagingSenderId: '975712420973',
    projectId: 'adiuva-aa007',
    storageBucket: 'adiuva-aa007.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtptVJtN3z43r-GYQBVNg55tgbntfZE8',
    appId: '1:975712420973:web:805594425112e2b6fceb64',
    messagingSenderId: '975712420973',
    projectId: 'adiuva-aa007',
    authDomain: 'adiuva-aa007.firebaseapp.com',
    storageBucket: 'adiuva-aa007.firebasestorage.app',
  );
}
